name: modmail
services:
  build_bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${PUID:?Missing PUID}
        DOCKER_USER_GID: ${PGID:?Missing PGID}
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - ./:/modmail
    networks:
      - network
    command: |-
      bash -c "cd /modmail && npm ci"
  bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${PUID:?Missing PUID}
        DOCKER_USER_GID: ${PGID:?Missing PGID}
    restart: on-failure
    security_opt:
      - "no-new-privileges:true"
    expose:
      - 8890
    depends_on:
      - build_bot
    volumes:
      - ./:/modmail
    networks:
      - network
      - traefik-proxy
    #environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailman.entrypoints=websecure"
      - "traefik.http.routers.mailman.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.mailman.tls.certresolver=http-challenge"
      - "traefik.http.services.mailman.loadbalancer.server.port=8890"
    command: ["/bin/bash", "/modmail/docker/start-modmail.sh"]
networks:
  network:
  traefik-proxy:
    external: true
