version: '3'
name: modmail
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: modmail
      MYSQL_USER: modmail
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --authentication-policy=mysql_native_password
    networks:
      - network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASE;\""
      interval: 5s
      timeout: 300s
      retries: 60
  build_bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${DOCKER_USER_UID:?Missing DOCKER_USER_UID}
        DOCKER_USER_GID: ${DOCKER_USER_GID:?Missing DOCKER_USER_GID}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/modmail
    networks:
      - network
    command: |-
      bash -c "cd /modmail && npm ci"
  bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${DOCKER_USER_UID:?Missing DOCKER_USER_UID}
        DOCKER_USER_GID: ${DOCKER_USER_GID:?Missing DOCKER_USER_GID}
    restart: on-failure
    expose:
      - ${MM_PORT:-8890}:${MM_PORT:-8890}
    depends_on:
      - build_bot
      - mysql
    volumes:
      - ./:/modmail
    networks:
      - network
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:?missing VIRTUAL_HOST}
      VIRTUAL_PATH: /
      #VIRTUAL_DEST:
      #VIRTUAL_PORT:
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:?missing VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      DEBUG: ${DEBUG:-false}
    command: ["/bin/bash", "/modmail/docker/start-modmail.sh"]
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://${VIRTUAL_HOST:?Missing VIRTUAL_HOST}/phpmyadmin/
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_USER: modmail
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST:?Missing VIRTUAL_HOST}
      VIRTUAL_PATH: /phpmyadmin
      VIRTUAL_DEST: /
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:?Missing VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      DEBUG: ${DEBUG:-false}
    networks:
      - network
      - nginx-proxy
networks:
  network:
  nginx-proxy:
    name: nginx-proxy
    external: true