#name: modmail
services:
  mysql:
    image: mysql:8.0
    security_opt:
      - "no-new-privileges:true"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: modmail
      MYSQL_USER: modmail
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --authentication-policy=mysql_native_password
    networks:
      - network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASE;\""
      interval: 5s
      timeout: 300s
      retries: 60
  build_bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${PUID:?Missing PUID}
        DOCKER_USER_GID: ${PGID:?Missing PGID}
    depends_on:
      mysql:
        condition: service_healthy
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - ./:/modmail
    networks:
      - network
    command: |-
      bash -c "cd /modmail && npm ci && npm run run-migrations"
  bot:
    build:
      context: ./docker/node
      args:
        DOCKER_USER_UID: ${PUID:?Missing PUID}
        DOCKER_USER_GID: ${PGID:?Missing PGID}
    restart: on-failure
    security_opt:
      - "no-new-privileges:true"
    expose:
      - 8890
    depends_on:
      - build_bot
      - mysql
    volumes:
      - ./:/modmail
    networks:
      - network
      - nginx-proxy
    environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=http-challenge"
      - "traefik.http.services.mailman.loadbalancer.server.port=8890"
    command: ["/bin/bash", "/modmail/docker/start-modmail.sh"]
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: unless-stopped
    expose:
      - "80"
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - SETUID
      - SETGID
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://${DOMAIN:?Missing DOMAIN}/phpmyadmin/
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_USER: modmail
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.rule=Host(`$DOMAIN`) && PathPrefix(`/phpmyadmin`)"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=http-challenge"
    networks:
      - network
      - traefik-proxy
networks:
  network:
  traefik-proxy:
    external: true
